apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "invoiceninja.fullname" . }}-env
  labels:
    app: {{ template "invoiceninja.name" . }}
    chart: {{ template "invoiceninja.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.envconfig }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    DB_HOST1: {{ .Release.Name }}-mysql

